name: CI del backend a Dockerhub

on:
  push:
    branches: [ develop ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Login de Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir a DockerHub
        uses: docker/build-push-action
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jblas7/test-ci:v${{ github.run_number }}